# Generated by Django 4.2.11 on 2024-04-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historicalfooditem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
