# Generated by Django 4.2.11 on 2024-04-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_fooditem_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodlog',
            options={'ordering': ['date_logged']},
        ),
    ]
